### ISSUE TITLE
Possible to get stuck with head between blocks

### ISSUE THREAD

**Issue by lifelike** [LarsBergqvist/star-hunter-game#1]
Testing this we noticed that you can get stuck with your head between blocks. Noticed on
level 1 when falling down at about 18,-3 (in the tile map coordinates).

**Comment by lifelike** [comment]
My 9yo found this when we were playing around with the game to experiment a bit and learn godot btw. :) Pull request incoming.

**Comment by LarsBergqvist** [comment]
Thanks for trying it out and spotting the problem! And also thanks for figuring out a nice simple fix. I accept the pull request.
